"""add related_person to charge and payment

Revision ID: 0f446a1369f4
Revises: 6cfb7be7e25a
Create Date: 2026-09-02 11:39:08.270500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f446a1369f4'
down_revision: Union[str, Sequence[str], None] = '6cfb7be7e25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_person_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_charge_related_person_id'), ['related_person_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_charge_related_person_id_person'), 'person', ['related_person_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_person_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_related_person_id'), ['related_person_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_payment_related_person_id_person'), 'person', ['related_person_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_related_person_id_person'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_related_person_id'))
        batch_op.drop_column('related_person_id')

    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_charge_related_person_id_person'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_charge_related_person_id'))
        batch_op.drop_column('related_person_id')

    # ### end Alembic commands ###
