"""add unique constraint to annual report meeting id

Один годовой отчёт (annual_report) на одно годовое отчётное собрание
(general_meeting) — раньше это была бы только проверка в коде
(app/annual_reports.py), теперь держит и сама БД. Таблица пуста, бэкофилл
не нужен.

Revision ID: 0f5128cac9ff
Revises: db0345965ad2
Create Date: 2026-09-08 21:37:45.913938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5128cac9ff'
down_revision: Union[str, Sequence[str], None] = 'db0345965ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annual_report_meeting_id'))
        batch_op.create_index(batch_op.f('ix_annual_report_meeting_id'), ['meeting_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annual_report_meeting_id'))
        batch_op.create_index(batch_op.f('ix_annual_report_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###
