"""add board chat

Чат правления (плавающий виджет на всех страницах, см. app/board_chat.py)
— board_chat_message новая таблица, user.board_chat_read_at новая
nullable-колонка, без бэкофилла.

Revision ID: 23455db5ee9f
Revises: fa52a847d8a6
Create Date: 2026-09-06 18:18:35.870401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23455db5ee9f'
down_revision: Union[str, Sequence[str], None] = 'fa52a847d8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_board_chat_message_author_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_chat_message'))
    )
    with op.batch_alter_table('board_chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_chat_message_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_chat_message_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_chat_read_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('board_chat_read_at')

    with op.batch_alter_table('board_chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_chat_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_board_chat_message_author_id'))

    op.drop_table('board_chat_message')
    # ### end Alembic commands ###
