"""add account number matching to bank statement lines

Revision ID: 27479a13e37d
Revises: d78a43b35267
Create Date: 2026-08-25 20:56:27.479763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27479a13e37d'
down_revision: Union[str, Sequence[str], None] = 'd78a43b35267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('matched_payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bank_statement_line_matched_payment_id_payment'), 'payment', ['matched_payment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bank_statement_line_matched_payment_id_payment'), type_='foreignkey')
        batch_op.drop_column('matched_payment_id')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
