"""add vote proposals

Revision ID: 2795a1444511
Revises: 5300dca34cc6
Create Date: 2026-09-02 07:57:04.876253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2795a1444511'
down_revision: Union[str, Sequence[str], None] = '5300dca34cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('proposed_by_person_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_vote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_by_person_id'], ['person.id'], name=op.f('fk_vote_proposal_proposed_by_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_vote_id'], ['vote.id'], name=op.f('fk_vote_proposal_resulting_vote_id_vote'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_proposal'))
    )
    with op.batch_alter_table('vote_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_proposal_proposed_by_person_id'), ['proposed_by_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_proposal_resulting_vote_id'), ['resulting_vote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_proposal_status'), ['status'], unique=False)

    op.create_table('vote_proposal_board_ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', name='votechoice'), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_vote_proposal_board_ballot_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['vote_proposal.id'], name=op.f('fk_vote_proposal_board_ballot_proposal_id_vote_proposal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_proposal_board_ballot')),
    sa.UniqueConstraint('proposal_id', 'person_id', name='uq_vote_proposal_ballot_proposal_person')
    )
    with op.batch_alter_table('vote_proposal_board_ballot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_proposal_board_ballot_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_proposal_board_ballot_proposal_id'), ['proposal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_proposal_board_ballot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_proposal_board_ballot_proposal_id'))
        batch_op.drop_index(batch_op.f('ix_vote_proposal_board_ballot_person_id'))

    op.drop_table('vote_proposal_board_ballot')
    with op.batch_alter_table('vote_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_vote_proposal_resulting_vote_id'))
        batch_op.drop_index(batch_op.f('ix_vote_proposal_proposed_by_person_id'))

    op.drop_table('vote_proposal')
    # ### end Alembic commands ###
