"""add dvr recorder and camera tables

Revision ID: 2a3c649e8b11
Revises: 72db29c61bd3
Create Date: 2026-09-03 13:40:04.576100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3c649e8b11'
down_revision: Union[str, Sequence[str], None] = '72db29c61bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 'cooperative.garage_area' drop вырезан вручную — это не наше изменение,
    # а посторонний дрейф dev-БД (колонка убрана из модели ещё в миграции
    # 2a97e92adbab, но в БД этой сессии почему-то ещё жива) — повторяется в
    # каждом autogenerate этой сессии, см. историю коммитов.
    op.create_table('dvr_recorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dvr_recorder'))
    )
    op.create_table('dvr_camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorder_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('stream', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('last_snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recorder_id'], ['dvr_recorder.id'], name=op.f('fk_dvr_camera_recorder_id_dvr_recorder'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dvr_camera'))
    )
    with op.batch_alter_table('dvr_camera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dvr_camera_recorder_id'), ['recorder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dvr_camera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dvr_camera_recorder_id'))

    op.drop_table('dvr_camera')
    op.drop_table('dvr_recorder')
    # ### end Alembic commands ###
