"""add public comment to vote ballots

Revision ID: 2b97a3a3dd71
Revises: 2795a1444511
Create Date: 2026-09-02 08:29:04.038238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b97a3a3dd71'
down_revision: Union[str, Sequence[str], None] = '2795a1444511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_ballot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    with op.batch_alter_table('vote_proposal_board_ballot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_proposal_board_ballot', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('vote_ballot', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
