"""baseline: текущая схема БД

Revision ID: 2c8e0f8015a7
Revises: 
Create Date: 2026-08-15 16:13:08.377753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8e0f8015a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_number_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_digits', sa.Integer(), nullable=False),
    sa.Column('owner_digits', sa.Integer(), nullable=False),
    sa.Column('electricity_prefix', sa.String(length=10), nullable=False),
    sa.Column('penalty_prefix', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bik', sa.String(length=9), nullable=True),
    sa.Column('checking_account', sa.String(length=20), nullable=False),
    sa.Column('correspondent_account', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('ogrn', sa.String(length=15), nullable=False),
    sa.Column('legal_address', sa.Text(), nullable=True),
    sa.Column('postal_address', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('total_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('garage_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('common_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('standard_garage_land_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('land_tax_rate_percent', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('bank_fee_percent', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_table('counterparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('CHARTER', 'ORDER', 'ACT', 'LETTER', 'PROTOCOL', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_doc_type'), ['doc_type'], unique=False)

    op.create_table('electricity_tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electricity_tariff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_electricity_tariff_effective_date'), ['effective_date'], unique=False)

    op.create_table('fee_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('type_code', sa.String(length=5), nullable=True),
    sa.Column('is_penalty', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('garage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('land_privatized', sa.Boolean(), nullable=False),
    sa.Column('cadastral_number', sa.String(length=50), nullable=True),
    sa.Column('land_cadastral_number', sa.String(length=50), nullable=True),
    sa.Column('privatized_land_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('land_tax_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cadastral_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('registration_address', sa.Text(), nullable=True),
    sa.Column('residence_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telegram', sa.String(length=120), nullable=True),
    sa.Column('passport_series', sa.String(length=4), nullable=True),
    sa.Column('passport_number', sa.String(length=6), nullable=True),
    sa.Column('passport_issued_by', sa.Text(), nullable=True),
    sa.Column('passport_issue_date', sa.Date(), nullable=True),
    sa.Column('passport_department_code', sa.String(length=7), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('membership_start_date', sa.Date(), nullable=True),
    sa.Column('membership_end_date', sa.Date(), nullable=True),
    sa.Column('is_board_member', sa.Boolean(), nullable=False),
    sa.Column('is_chairman', sa.Boolean(), nullable=False),
    sa.Column('is_accountant', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_full_name'), ['full_name'], unique=False)
        batch_op.create_index('uq_single_chairman', ['is_chairman'], unique=True, sqlite_where=sa.text('is_chairman = 1'))

    op.create_table('electricity_meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('meter_number', sa.String(length=50), nullable=False),
    sa.Column('installed_date', sa.Date(), nullable=True),
    sa.Column('sealed_date', sa.Date(), nullable=True),
    sa.Column('initial_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('meter_seal_number', sa.String(length=50), nullable=True),
    sa.Column('breaker_seal_number', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electricity_meter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_electricity_meter_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electricity_meter_installed_date'), ['installed_date'], unique=False)

    op.create_table('electricity_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['counterparty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_document_id'), ['document_id'], unique=False)

    op.create_table('garage_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garage_contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_contact_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_contact_person_id'), ['person_id'], unique=False)

    op.create_table('garage_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('share', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.CheckConstraint('share > 0 AND share <= 1', name='ck_share_range'),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garage_id', 'person_id', name='uq_ownership_garage_person')
    )
    with op.batch_alter_table('garage_ownership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_ownership_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_ownership_person_id'), ['person_id'], unique=False)

    op.create_table('garage_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garage_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_photo_garage_id'), ['garage_id'], unique=False)

    op.create_table('general_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('is_annual_report_meeting', sa.Boolean(), nullable=False),
    sa.Column('secretary_person_id', sa.Integer(), nullable=True),
    sa.Column('chairman_person_id', sa.Integer(), nullable=True),
    sa.Column('protocol_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chairman_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secretary_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_meeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_meeting_chairman_person_id'), ['chairman_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_meeting_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_meeting_protocol_document_id'), ['protocol_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_general_meeting_secretary_person_id'), ['secretary_person_id'], unique=False)

    op.create_table('master_meter_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('reading', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tariff_id'], ['electricity_tariff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_meter_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_meter_reading_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_meter_reading_reading_date'), ['reading_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_meter_reading_tariff_id'), ['tariff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_meter_reading_year'), ['year'], unique=False)

    op.create_table('member_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_type.id'], ),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('person_id', 'garage_id', 'fee_type_id', name='uq_member_account')
    )
    with op.batch_alter_table('member_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_account_fee_type_id'), ['fee_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_account_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_account_person_id'), ['person_id'], unique=False)

    op.create_table('personal_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('garage_id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_person_id'), ['person_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CHAIRMAN', 'BOARD', 'ACCOUNTANT', 'MEMBER', name='roleenum'), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('annual_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('spending_report_document_id', sa.Integer(), nullable=True),
    sa.Column('accounting_report_document_id', sa.Integer(), nullable=True),
    sa.Column('budget_approved', sa.Boolean(), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accounting_report_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['general_meeting.id'], ),
    sa.ForeignKeyConstraint(['spending_report_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annual_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annual_report_accounting_report_document_id'), ['accounting_report_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annual_report_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annual_report_spending_report_document_id'), ['spending_report_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annual_report_year'), ['year'], unique=False)

    op.create_table('board_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('elected_by_meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elected_by_meeting_id'], ['general_meeting.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_term_elected_by_meeting_id'), ['elected_by_meeting_id'], unique=False)

    op.create_table('electricity_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tariff', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['electricity_meter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electricity_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_electricity_reading_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electricity_reading_reading_date'), ['reading_date'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payer_person_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('(garage_id IS NOT NULL) + (account_id IS NOT NULL) = 1', name='ck_payment_target'),
    sa.ForeignKeyConstraint(['account_id'], ['member_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_payer_person_id'), ['payer_person_id'], unique=False)

    op.create_table('pd4_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('personal_account_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(account_id IS NOT NULL) + (personal_account_id IS NOT NULL) = 1', name='ck_pd4_document_target'),
    sa.ForeignKeyConstraint(['account_id'], ['member_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personal_account_id'], ['personal_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pd4_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pd4_document_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pd4_document_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pd4_document_personal_account_id'), ['personal_account_id'], unique=False)

    op.create_table('person_data_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='persondatarevisionstatus'), nullable=False),
    sa.Column('fields_snapshot', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_data_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_data_revision_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_data_revision_reviewer_user_id'), ['reviewer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_data_revision_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    op.create_table('board_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_chairman', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['board_term.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'person_id', name='uq_board_member_term_person')
    )
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_member_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_member_term_id'), ['term_id'], unique=False)

    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('fee_type_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('(garage_id IS NOT NULL) + (account_id IS NOT NULL) = 1', name='ck_charge_target'),
    sa.ForeignKeyConstraint(['account_id'], ['member_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_report.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_type.id'], ),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_id'], ['electricity_reading.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_annual_report_id'), ['annual_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_fee_type_id'), ['fee_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_reading_id'), ['reading_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_year'), ['year'], unique=False)

    op.create_table('fee_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('fee_type_id', sa.Integer(), nullable=False),
    sa.Column('rate_per_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_report.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_rate_annual_report_id'), ['annual_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_rate_fee_type_id'), ['fee_type_id'], unique=False)

    op.create_table('charge_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_allocation_charge_id'), ['charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_allocation_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_allocation_payment_id'))
        batch_op.drop_index(batch_op.f('ix_charge_allocation_charge_id'))

    op.drop_table('charge_allocation')
    with op.batch_alter_table('fee_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rate_fee_type_id'))
        batch_op.drop_index(batch_op.f('ix_fee_rate_annual_report_id'))

    op.drop_table('fee_rate')
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_year'))
        batch_op.drop_index(batch_op.f('ix_charge_reading_id'))
        batch_op.drop_index(batch_op.f('ix_charge_garage_id'))
        batch_op.drop_index(batch_op.f('ix_charge_fee_type_id'))
        batch_op.drop_index(batch_op.f('ix_charge_annual_report_id'))
        batch_op.drop_index(batch_op.f('ix_charge_account_id'))

    op.drop_table('charge')
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_member_term_id'))
        batch_op.drop_index(batch_op.f('ix_board_member_person_id'))

    op.drop_table('board_member')
    with op.batch_alter_table('person_data_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_data_revision_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_person_data_revision_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_person_data_revision_person_id'))

    op.drop_table('person_data_revision')
    with op.batch_alter_table('pd4_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pd4_document_personal_account_id'))
        batch_op.drop_index(batch_op.f('ix_pd4_document_bank_account_id'))
        batch_op.drop_index(batch_op.f('ix_pd4_document_account_id'))

    op.drop_table('pd4_document')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_payer_person_id'))
        batch_op.drop_index(batch_op.f('ix_payment_garage_id'))
        batch_op.drop_index(batch_op.f('ix_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payment_account_id'))

    op.drop_table('payment')
    with op.batch_alter_table('electricity_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_electricity_reading_reading_date'))
        batch_op.drop_index(batch_op.f('ix_electricity_reading_meter_id'))

    op.drop_table('electricity_reading')
    with op.batch_alter_table('board_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_term_elected_by_meeting_id'))

    op.drop_table('board_term')
    with op.batch_alter_table('annual_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annual_report_year'))
        batch_op.drop_index(batch_op.f('ix_annual_report_spending_report_document_id'))
        batch_op.drop_index(batch_op.f('ix_annual_report_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_annual_report_accounting_report_document_id'))

    op.drop_table('annual_report')
    op.drop_table('user')
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_person_id'))

    op.drop_table('phone')
    op.drop_table('personal_account')
    with op.batch_alter_table('member_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_account_person_id'))
        batch_op.drop_index(batch_op.f('ix_member_account_garage_id'))
        batch_op.drop_index(batch_op.f('ix_member_account_fee_type_id'))

    op.drop_table('member_account')
    with op.batch_alter_table('master_meter_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_meter_reading_year'))
        batch_op.drop_index(batch_op.f('ix_master_meter_reading_tariff_id'))
        batch_op.drop_index(batch_op.f('ix_master_meter_reading_reading_date'))
        batch_op.drop_index(batch_op.f('ix_master_meter_reading_document_id'))

    op.drop_table('master_meter_reading')
    with op.batch_alter_table('general_meeting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_meeting_secretary_person_id'))
        batch_op.drop_index(batch_op.f('ix_general_meeting_protocol_document_id'))
        batch_op.drop_index(batch_op.f('ix_general_meeting_date'))
        batch_op.drop_index(batch_op.f('ix_general_meeting_chairman_person_id'))

    op.drop_table('general_meeting')
    with op.batch_alter_table('garage_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_photo_garage_id'))

    op.drop_table('garage_photo')
    with op.batch_alter_table('garage_ownership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_ownership_person_id'))
        batch_op.drop_index(batch_op.f('ix_garage_ownership_garage_id'))

    op.drop_table('garage_ownership')
    with op.batch_alter_table('garage_contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_contact_person_id'))
        batch_op.drop_index(batch_op.f('ix_garage_contact_garage_id'))

    op.drop_table('garage_contact')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_document_id'))
        batch_op.drop_index(batch_op.f('ix_expense_counterparty_id'))

    op.drop_table('expense')
    op.drop_table('electricity_settings')
    with op.batch_alter_table('electricity_meter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_electricity_meter_installed_date'))
        batch_op.drop_index(batch_op.f('ix_electricity_meter_garage_id'))

    op.drop_table('electricity_meter')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('uq_single_chairman', sqlite_where=sa.text('is_chairman = 1'))
        batch_op.drop_index(batch_op.f('ix_person_full_name'))

    op.drop_table('person')
    op.drop_table('land_tax_year')
    op.drop_table('garage')
    op.drop_table('fee_type')
    with op.batch_alter_table('electricity_tariff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_electricity_tariff_effective_date'))

    op.drop_table('electricity_tariff')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_doc_type'))
        batch_op.drop_index(batch_op.f('ix_document_date'))

    op.drop_table('document')
    op.drop_table('counterparty')
    op.drop_table('cooperative')
    op.drop_table('bank_account')
    op.drop_table('account_number_settings')
    # ### end Alembic commands ###
