"""add garage as control meter parent

Контрольный узел может быть физически запитан через щиток конкретного
гаража, а не от ввода/другого узла дерева (напр. общее освещение через
абонентский счётчик) — control_meter.parent_garage_id, взаимоисключающий
с parent_id (ck_control_meter_single_parent). ElectricityReading получает
control_meter_deduction — сколько кВт·ч из дельты показания вычтено как
потребление таких узлов при начислении (см. app/control_meters.py,
app/garages.py).

Revision ID: 32703cc73c83
Revises: 7cb7830bdcc9
Create Date: 2026-09-21 10:57:21.981464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32703cc73c83'
down_revision: Union[str, Sequence[str], None] = '7cb7830bdcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_meter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_garage_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_control_meter_parent_garage_id'), ['parent_garage_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_control_meter_parent_garage_id_garage'), 'garage', ['parent_garage_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_check_constraint(batch_op.f('ck_control_meter_ck_control_meter_single_parent'), 'NOT (parent_id IS NOT NULL AND parent_garage_id IS NOT NULL)')

    with op.batch_alter_table('electricity_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_meter_deduction', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electricity_reading', schema=None) as batch_op:
        batch_op.drop_column('control_meter_deduction')

    with op.batch_alter_table('control_meter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_control_meter_ck_control_meter_single_parent'), type_='check')
        batch_op.drop_constraint(batch_op.f('fk_control_meter_parent_garage_id_garage'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_control_meter_parent_garage_id'))
        batch_op.drop_column('parent_garage_id')

    # ### end Alembic commands ###
