"""add sms log

Revision ID: 339bc8ea5507
Revises: 8ea4ad8474d7
Create Date: 2026-09-07 15:46:58.456805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339bc8ea5507'
down_revision: Union[str, Sequence[str], None] = '8ea4ad8474d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='smslogstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_log'))
    )
    with op.batch_alter_table('sms_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_log_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_log_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_log_status'))
        batch_op.drop_index(batch_op.f('ix_sms_log_sent_at'))

    op.drop_table('sms_log')
    # ### end Alembic commands ###
