"""add forum

Форум (`/forum/`, app/forum.py) — свободное обсуждение любых вопросов
вошедшими членами кооператива, три новые таблицы: forum_topic (тема),
forum_post (сообщение — и открывающее, и ответы, одна модель), а таблица
forum_attachment — inline-картинки в тексте сообщения (1-в-1
bulletin_attachment). Новая функциональность, бэкофилл не нужен.

Revision ID: 35e0b519fb7e
Revises: 0f5128cac9ff
Create Date: 2026-09-09 13:17:17.526261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e0b519fb7e'
down_revision: Union[str, Sequence[str], None] = '0f5128cac9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_forum_topic_author_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_topic'))
    )
    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_topic_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_topic_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_topic_last_activity_at'), ['last_activity_at'], unique=False)

    op.create_table('forum_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_forum_post_author_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['forum_topic.id'], name=op.f('fk_forum_post_topic_id_forum_topic'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_post'))
    )
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_post_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_topic_id'), ['topic_id'], unique=False)

    op.create_table('forum_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_forum_attachment_author_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.id'], name=op.f('fk_forum_attachment_post_id_forum_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_attachment'))
    )
    with op.batch_alter_table('forum_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_attachment_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_attachment_is_inline'), ['is_inline'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_attachment_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_attachment_post_id'))
        batch_op.drop_index(batch_op.f('ix_forum_attachment_is_inline'))
        batch_op.drop_index(batch_op.f('ix_forum_attachment_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_attachment_author_id'))

    op.drop_table('forum_attachment')
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_post_topic_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_post_author_id'))

    op.drop_table('forum_post')
    with op.batch_alter_table('forum_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_topic_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_forum_topic_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_topic_author_id'))

    op.drop_table('forum_topic')
    # ### end Alembic commands ###
