"""add sberbank mtls cert fields

Revision ID: 3a1d3637b8da
Revises: a1f14574f3e5
Create Date: 2026-08-24 23:51:32.071214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1d3637b8da'
down_revision: Union[str, Sequence[str], None] = 'a1f14574f3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_api_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tls_cert_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tls_key_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_api_credential', schema=None) as batch_op:
        batch_op.drop_column('tls_key_filename')
        batch_op.drop_column('tls_cert_filename')

    # ### end Alembic commands ###
