"""add court_section

Revision ID: 3ad945edce9a
Revises: 2957b5de4c5c
Create Date: 2026-09-06 20:25:52.807459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad945edce9a'
down_revision: Union[str, Sequence[str], None] = '2957b5de4c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('court_address', sa.Text(), nullable=True),
    sa.Column('treasury_payee', sa.String(length=255), nullable=True),
    sa.Column('treasury_inn', sa.String(length=12), nullable=True),
    sa.Column('treasury_kpp', sa.String(length=9), nullable=True),
    sa.Column('treasury_bank', sa.String(length=255), nullable=True),
    sa.Column('treasury_account', sa.String(length=20), nullable=True),
    sa.Column('treasury_bik', sa.String(length=9), nullable=True),
    sa.Column('treasury_correspondent_account', sa.String(length=20), nullable=True),
    sa.Column('treasury_oktmo', sa.String(length=11), nullable=True),
    sa.Column('treasury_kbk', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court_section'))
    )
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_court_section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cooperative_default_court_section_id'), ['default_court_section_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_cooperative_default_court_section_id_court_section'), 'court_section', ['default_court_section_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('court_section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_person_court_section_id'), ['court_section_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_person_court_section_id_court_section'), 'court_section', ['court_section_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_person_court_section_id_court_section'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_person_court_section_id'))
        batch_op.drop_column('court_section_id')

    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cooperative_default_court_section_id_court_section'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cooperative_default_court_section_id'))
        batch_op.drop_column('default_court_section_id')

    op.drop_table('court_section')
    # ### end Alembic commands ###
