"""add person archive fields

Revision ID: 3ba08d3a4c40
Revises: 4503eff2c674
Create Date: 2026-09-01 02:24:37.632569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba08d3a4c40'
down_revision: Union[str, Sequence[str], None] = '4503eff2c674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        # server_default нужен только на время добавления колонки — у уже
        # существующих людей (не первый деплой) is_archived нигде раньше
        # не задавался, безопасное значение по умолчанию — False (не в
        # архиве), сохраняет прежнее поведение (все были видны в общем
        # списке), см. context.md.
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('archived_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_person_is_archived'), ['is_archived'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_person_archived_by_user_id_user'), 'user', ['archived_by_user_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('is_archived', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_person_archived_by_user_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_person_is_archived'))
        batch_op.drop_column('archived_by_user_id')
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
