"""add wiki page table

Revision ID: 3c06185c2e9e
Revises: 379d97c98c74
Create Date: 2026-08-29 22:01:15.852721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c06185c2e9e'
down_revision: Union[str, Sequence[str], None] = '379d97c98c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_wiki_page_author_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_wiki_page_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_page'))
    )
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_is_internal'), ['is_internal'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_updated_by_id'), ['updated_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_updated_by_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_is_internal'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_category'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_author_id'))

    op.drop_table('wiki_page')
    # ### end Alembic commands ###
