"""add inline image attachments for news and wiki

Добавляет возможность встраивать картинки прямо в тело новости/страницы
вики (![](url) в markdown, см. app/news_format.py — тег img разрешён в
bleach) вместо (точнее, в дополнение к) отдельной галереи под текстом.

- news_attachment.news_id становится nullable + новые колонки is_inline/
  author_id/created_at: картинка, вставленная через тулбар «Вставить
  картинку», загружается AJAX'ом ДО сохранения самой статьи (news_id ещё
  не существует — «осиротевшее» вложение), при сохранении привязывается
  к статье (см. app/news.py: _sync_inline_attachments). Бэкофилл для уже
  существующих строк: is_inline=False (это старые галерейные вложения, не
  встроенные), created_at — раз точного времени загрузки для них нет,
  берём момент выполнения миграции (см. ниже, тот же принцип, что и в
  57671066ae31 для is_internal — временный server_default только на время
  бэкофилла, дальше приложение всегда задаёт значение явно).
- wiki_attachment — новая таблица, тот же принцип для вики (app/wiki.py).

Revision ID: 3d0ecf5086aa
Revises: 3c06185c2e9e
Create Date: 2026-08-30 05:03:36.475586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0ecf5086aa'
down_revision: Union[str, Sequence[str], None] = '3c06185c2e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('wiki_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_wiki_attachment_author_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_page.id'], name=op.f('fk_wiki_attachment_page_id_wiki_page'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_attachment'))
    )
    with op.batch_alter_table('wiki_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_attachment_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_attachment_page_id'), ['page_id'], unique=False)
    # wiki_attachment — новая таблица, у неё в момент создания нет строк —
    # server_default на created_at ей не нужен (в отличие от news_attachment
    # ниже, где бэкофилл существующих строк обязателен).

    with op.batch_alter_table('news_attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_inline', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.alter_column('news_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_news_attachment_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_attachment_is_inline'), ['is_inline'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_news_attachment_author_id_user'), 'user', ['author_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('news_attachment', schema=None) as batch_op:
        batch_op.alter_column('is_inline', server_default=None)
        batch_op.alter_column('created_at', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_attachment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_news_attachment_author_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_news_attachment_is_inline'))
        batch_op.drop_index(batch_op.f('ix_news_attachment_created_at'))
        batch_op.drop_index(batch_op.f('ix_news_attachment_author_id'))
        batch_op.alter_column('news_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('author_id')
        batch_op.drop_column('is_inline')

    with op.batch_alter_table('wiki_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_attachment_page_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_attachment_created_at'))
        batch_op.drop_index(batch_op.f('ix_wiki_attachment_author_id'))

    op.drop_table('wiki_attachment')
    # ### end Alembic commands ###
