"""add garage ownership history

Revision ID: 4503eff2c674
Revises: 36ebefe01ade
Create Date: 2026-08-31 18:58:33.422002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4503eff2c674'
down_revision: Union[str, Sequence[str], None] = 'e80abefa5b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_ownership_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ADDED', 'SHARE_CHANGED', 'REMOVED', name='garageownershipeventtype'), nullable=False),
    sa.Column('share', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_garage_ownership_event_created_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], name=op.f('fk_garage_ownership_event_garage_id_garage'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_garage_ownership_event_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_garage_ownership_event'))
    )
    with op.batch_alter_table('garage_ownership_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_ownership_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_ownership_event_garage_id'), ['garage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_ownership_event_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_ownership_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_ownership_event_person_id'))
        batch_op.drop_index(batch_op.f('ix_garage_ownership_event_garage_id'))
        batch_op.drop_index(batch_op.f('ix_garage_ownership_event_created_at'))

    op.drop_table('garage_ownership_event')
    # ### end Alembic commands ###
