"""switch sberbank auth to refresh token

Revision ID: 4deb675b904f
Revises: 27479a13e37d
Create Date: 2026-08-27 04:32:28.649180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4deb675b904f'
down_revision: Union[str, Sequence[str], None] = '27479a13e37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_api_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_api_credential', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_encrypted')

    # ### end Alembic commands ###
