"""add counterparty opening balance and payment reversal link

Revision ID: 53b80161436b
Revises: 9f11637e275c
Create Date: 2026-08-17 03:10:07.414115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b80161436b'
down_revision: Union[str, Sequence[str], None] = '9f11637e275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('opening_balance_date', sa.Date(), nullable=True))

    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reverses_payment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counterparty_payment_reverses_payment_id'), ['reverses_payment_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_counterparty_payment_reverses_payment_id_counterparty_payment'), 'counterparty_payment', ['reverses_payment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_counterparty_payment_reverses_payment_id_counterparty_payment'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counterparty_payment_reverses_payment_id'))
        batch_op.drop_column('reverses_payment_id')

    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.drop_column('opening_balance_date')
        batch_op.drop_column('opening_balance')

    # ### end Alembic commands ###
