"""add previous_snapshot to person_data_revision

Revision ID: 55f9d7b0def0
Revises: eee538fb18a3
Create Date: 2026-09-01 18:42:20.951345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f9d7b0def0'
down_revision: Union[str, Sequence[str], None] = 'eee538fb18a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_data_revision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_data_revision', schema=None) as batch_op:
        batch_op.drop_column('previous_snapshot')

    # ### end Alembic commands ###
