"""add document type extension and internal flag

Расширяет DocumentType новыми видами документов (счета, выписки, справки,
смета, отчёт) и добавляет Document.is_internal — разделение документов на
общедоступные (видны всем вошедшим членам, прежнее поведение) и внутренние
(видны только правлению). См. app/documents.py и app/permissions.is_board().

Revision ID: 57671066ae31
Revises: 2a97e92adbab
Create Date: 2026-08-29 06:20:52.124643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57671066ae31'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        # server_default нужен только на время добавления колонки — у уже
        # существующих документов (если это не первый деплой) старое
        # поведение было «видно всем вошедшим», поэтому бэкофилл в False
        # (общедоступный), а не True — иначе ранее загруженные документы
        # внезапно стали бы недоступны рядовым членам после апгрейда.
        # Дальше server_default убирается: на уровне приложения значение
        # всегда задаётся явно (Document.is_internal берётся из чекбокса
        # формы, см. app/documents.py), потребности держать его в схеме
        # БД нет — тот же приём, что и в a1f14574f3e5_add_bank_api_integration.
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('doc_type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('CHARTER', 'ORDER', 'ACT', 'LETTER', 'PROTOCOL', 'INVOICE', 'STATEMENT', 'CERTIFICATE', 'ESTIMATE', 'REPORT', 'OTHER', name='documenttype'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_document_is_internal'), ['is_internal'], unique=False)
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('is_internal', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_is_internal'))
        batch_op.alter_column('doc_type',
               existing_type=sa.Enum('CHARTER', 'ORDER', 'ACT', 'LETTER', 'PROTOCOL', 'INVOICE', 'STATEMENT', 'CERTIFICATE', 'ESTIMATE', 'REPORT', 'OTHER', name='documenttype'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###
