"""add email and website to cooperative

Для отображения в реквизитах кооператива и в шапке официальных печатных
документов (см. app/templates/persons/statement.html, penalty_calculation.html).

Revision ID: 61dfe5611269
Revises: c66bd8825ef2
Create Date: 2026-09-04 08:43:45.112218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61dfe5611269'
down_revision: Union[str, Sequence[str], None] = 'c66bd8825ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
