"""add webpush subscriptions

Revision ID: 62f3a0a3bdba
Revises: 984230c7eb17
Create Date: 2026-09-09 22:35:26.916762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f3a0a3bdba'
down_revision: Union[str, Sequence[str], None] = '984230c7eb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('private_key_encrypted', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webpush_settings'))
    )
    op.create_table('webpush_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_webpush_subscription_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webpush_subscription')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_webpush_subscription_endpoint'))
    )
    with op.batch_alter_table('webpush_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webpush_subscription_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webpush_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webpush_subscription_user_id'))

    op.drop_table('webpush_subscription')
    op.drop_table('webpush_settings')
    # ### end Alembic commands ###
