"""add board member accountant flag and revision commission

Revision ID: 681177a9a365
Revises: 53b80161436b
Create Date: 2026-08-18 20:39:51.913460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681177a9a365'
down_revision: Union[str, Sequence[str], None] = '53b80161436b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('elected_by_meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elected_by_meeting_id'], ['general_meeting.id'], name=op.f('fk_revision_commission_elected_by_meeting_id_general_meeting'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_commission'))
    )
    with op.batch_alter_table('revision_commission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_commission_elected_by_meeting_id'), ['elected_by_meeting_id'], unique=False)

    op.create_table('revision_commission_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_chair', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['revision_commission.id'], name=op.f('fk_revision_commission_member_commission_id_revision_commission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_revision_commission_member_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision_commission_member')),
    sa.UniqueConstraint('commission_id', 'person_id', name='uq_revision_commission_member_commission_person')
    )
    with op.batch_alter_table('revision_commission_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revision_commission_member_commission_id'), ['commission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revision_commission_member_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accountant', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.drop_column('is_accountant')

    with op.batch_alter_table('revision_commission_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_commission_member_person_id'))
        batch_op.drop_index(batch_op.f('ix_revision_commission_member_commission_id'))

    op.drop_table('revision_commission_member')
    with op.batch_alter_table('revision_commission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revision_commission_elected_by_meeting_id'))

    op.drop_table('revision_commission')
    # ### end Alembic commands ###
