"""remove passport issued_by and department_code fields

Revision ID: 6cfb7be7e25a
Revises: f14327a9e7f5
Create Date: 2026-09-02 11:04:26.928690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfb7be7e25a'
down_revision: Union[str, Sequence[str], None] = 'f14327a9e7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('passport_issued_by')
        batch_op.drop_column('passport_department_code')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_department_code', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('passport_issued_by', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
