"""add bank_statement_line_id to counterparty_payment

Revision ID: 72db29c61bd3
Revises: e24720fd94ed
Create Date: 2026-09-03 11:32:13.189141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72db29c61bd3'
down_revision: Union[str, Sequence[str], None] = 'e24720fd94ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 'cooperative.garage_area' drop вырезан вручную — это не наше изменение,
    # а посторонний дрейф dev-БД (колонка убрана из модели уже давно, в
    # миграции 2a97e92adbab, но в БД этой сессии почему-то ещё жива) —
    # повторяется в каждом autogenerate этой сессии, см. историю коммитов.
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_statement_line_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counterparty_payment_bank_statement_line_id'), ['bank_statement_line_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_counterparty_payment_bank_statement_line_id_bank_statement_line'), 'bank_statement_line', ['bank_statement_line_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_counterparty_payment_bank_statement_line_id_bank_statement_line'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counterparty_payment_bank_statement_line_id'))
        batch_op.drop_column('bank_statement_line_id')

    # ### end Alembic commands ###
