"""add postal dispatch

Revision ID: 7cb7830bdcc9
Revises: c7cdbc691a17
Create Date: 2026-09-21 09:29:32.838362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb7830bdcc9'
down_revision: Union[str, Sequence[str], None] = 'c7cdbc691a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('reg_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EXPORTED', 'SENT', 'DELIVERED', 'FAILED', name='postaldispatchstatus'), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_postal_dispatch_created_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_postal_dispatch_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_postal_dispatch_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postal_dispatch')),
    sa.UniqueConstraint('reg_number', name=op.f('uq_postal_dispatch_reg_number'))
    )
    with op.batch_alter_table('postal_dispatch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postal_dispatch_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postal_dispatch_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postal_dispatch_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postal_dispatch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postal_dispatch_status'))
        batch_op.drop_index(batch_op.f('ix_postal_dispatch_person_id'))
        batch_op.drop_index(batch_op.f('ix_postal_dispatch_document_id'))

    op.drop_table('postal_dispatch')
    # ### end Alembic commands ###
