"""add ewelink phase monitoring

Revision ID: 878d06ce54f2
Revises: 744b79e224d6
Create Date: 2026-08-28 09:18:48.205475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878d06ce54f2'
down_revision: Union[str, Sequence[str], None] = '3ba08d3a4c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ewelink_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=True),
    sa.Column('app_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=4), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_obtained_at', sa.DateTime(), nullable=True),
    sa.Column('last_poll_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ewelink_account'))
    )
    op.create_table('power_phase_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('ewelink_device_id', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_power_phase_device')),
    sa.UniqueConstraint('ewelink_device_id', name=op.f('uq_power_phase_device_ewelink_device_id'))
    )
    op.create_table('power_phase_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('power_w', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voltage_v', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current_a', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('raw_params', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['power_phase_device.id'], name=op.f('fk_power_phase_reading_device_id_power_phase_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_power_phase_reading'))
    )
    with op.batch_alter_table('power_phase_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_power_phase_reading_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_power_phase_reading_device_ts', ['device_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_phase_reading_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power_phase_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_phase_reading_ts'))
        batch_op.drop_index('ix_power_phase_reading_device_ts')
        batch_op.drop_index(batch_op.f('ix_power_phase_reading_device_id'))

    op.drop_table('power_phase_reading')
    op.drop_table('power_phase_device')
    op.drop_table('ewelink_account')
    # ### end Alembic commands ###
