"""add board chat presence fields

Revision ID: 8ea4ad8474d7
Revises: 3ad945edce9a
Create Date: 2026-09-07 09:06:02.815550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea4ad8474d7'
down_revision: Union[str, Sequence[str], None] = '3ad945edce9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    server_default=false нужен только на время добавления колонки — все
    существующие учётные записи ещё никогда не открывали чат правления с
    этой фичей, статус "открыт" им не нужен. Дальше server_default
    убирается: на уровне приложения значение всегда задаётся явно (тот же
    приём, что и в 19bf37b971fd_add_must_change_password_to_user).
    """
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_chat_last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('board_chat_open', sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('board_chat_open', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('board_chat_open')
        batch_op.drop_column('board_chat_last_seen_at')

    # ### end Alembic commands ###
