"""add balance to cooperative and bank_account

Revision ID: 937aea5b79e3
Revises: 2c8e0f8015a7
Create Date: 2026-08-16 03:43:59.980958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937aea5b79e3'
down_revision: Union[str, Sequence[str], None] = '2c8e0f8015a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('balance_updated_at', sa.Date(), nullable=True))

    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('balance_updated_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.drop_column('balance_updated_at')
        batch_op.drop_column('balance')

    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_column('balance_updated_at')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
