"""add garage document photo

Revision ID: 96561af74114
Revises: 53476a1af6cf
Create Date: 2026-09-05 17:47:54.017238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96561af74114'
down_revision: Union[str, Sequence[str], None] = '53476a1af6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_document_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('TECHNICAL_PLAN', 'USRN_EXTRACT', 'LAND_SURVEY', 'OTHER', name='garagedocumenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_garage_document_photo_author_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garage_id'], ['garage.id'], name=op.f('fk_garage_document_photo_garage_id_garage'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_garage_document_photo'))
    )
    with op.batch_alter_table('garage_document_photo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garage_document_photo_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_document_photo_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_document_photo_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_garage_document_photo_garage_id'), ['garage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_document_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garage_document_photo_garage_id'))
        batch_op.drop_index(batch_op.f('ix_garage_document_photo_doc_type'))
        batch_op.drop_index(batch_op.f('ix_garage_document_photo_created_at'))
        batch_op.drop_index(batch_op.f('ix_garage_document_photo_author_id'))

    op.drop_table('garage_document_photo')
    # ### end Alembic commands ###
