"""add telegram bot notifications, remove vk and max channels

Revision ID: 984230c7eb17
Revises: e379b7dc72bb
Create Date: 2026-09-09 22:11:32.933408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984230c7eb17'
down_revision: Union[str, Sequence[str], None] = 'e379b7dc72bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    notify_channel — обычный VARCHAR без CHECK-ограничения (SQLAlchemy
    Enum на SQLite не создаёт constraint по умолчанию), поэтому сужение
    набора значений VK/MAX -> только EMAIL/TELEGRAM не требует ALTER —
    достаточно очистить уже сохранённые VK/MAX (задел на будущее, реальных
    пользователей с этими значениями ещё не было, т.к. отправка через них
    никогда не была реализована)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token_encrypted', sa.Text(), nullable=True),
    sa.Column('bot_username', sa.String(length=64), nullable=True),
    sa.Column('last_update_id', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_settings'))
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('telegram_link_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_person_telegram_chat_id'), ['telegram_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_telegram_link_token'), ['telegram_link_token'], unique=True)

    # ### end Alembic commands ###

    op.execute("UPDATE user SET notify_channel = NULL WHERE notify_channel IN ('VK', 'MAX')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_telegram_link_token'))
        batch_op.drop_index(batch_op.f('ix_person_telegram_chat_id'))
        batch_op.drop_column('telegram_link_token')
        batch_op.drop_column('telegram_chat_id')

    op.drop_table('telegram_settings')
    # ### end Alembic commands ###
