"""add penalty automation: cooperative dues due date, key_rate table, charge penalty fields, member charge reallocation

Revision ID: 9a4dfa67d711
Revises: 9fda27835c78
Create Date: 2026-08-20 05:01:23.981007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4dfa67d711'
down_revision: Union[str, Sequence[str], None] = 'dbc01b5009be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_key_rate'))
    )
    with op.batch_alter_table('key_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_rate_effective_date'), ['effective_date'], unique=True)

    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty_calculated_through', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('penalty_for_charge_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_charge_penalty_for_charge_id'), ['penalty_for_charge_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_charge_penalty_for_charge_id_charge'), 'charge', ['penalty_for_charge_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dues_due_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dues_due_month', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.drop_column('dues_due_month')
        batch_op.drop_column('dues_due_day')

    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_charge_penalty_for_charge_id_charge'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_charge_penalty_for_charge_id'))
        batch_op.drop_column('penalty_for_charge_id')
        batch_op.drop_column('penalty_calculated_through')

    with op.batch_alter_table('key_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_rate_effective_date'))

    op.drop_table('key_rate')
    # ### end Alembic commands ###
