"""add counterparty payments, expense allocations, reconciliation acts

Revision ID: 9f11637e275c
Revises: 937aea5b79e3
Create Date: 2026-08-16 09:01:49.111146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f11637e275c'
down_revision: Union[str, Sequence[str], None] = '937aea5b79e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparty_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_counterparty_payment_bank_account_id_bank_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_counterparty_payment_counterparty_id_counterparty')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_counterparty_payment_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparty_payment'))
    )
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparty_payment_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_payment_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_payment_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_payment_document_id'), ['document_id'], unique=False)

    op.create_table('reconciliation_act',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('our_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('counterparty_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name=op.f('fk_reconciliation_act_counterparty_id_counterparty')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_reconciliation_act_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_act'))
    )
    with op.batch_alter_table('reconciliation_act', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_act_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_act_document_id'), ['document_id'], unique=False)

    op.create_table('expense_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_expense_allocation_expense_id_expense'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['counterparty_payment.id'], name=op.f('fk_expense_allocation_payment_id_counterparty_payment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_allocation'))
    )
    with op.batch_alter_table('expense_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_allocation_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_allocation_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('master_meter_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_master_meter_reading_expense_id'), ['expense_id'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_master_meter_reading_expense_id_expense'), 'expense', ['expense_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_meter_reading', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_master_meter_reading_expense_id_expense'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_master_meter_reading_expense_id'))
        batch_op.drop_column('expense_id')

    with op.batch_alter_table('expense_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_allocation_payment_id'))
        batch_op.drop_index(batch_op.f('ix_expense_allocation_expense_id'))

    op.drop_table('expense_allocation')
    with op.batch_alter_table('reconciliation_act', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_act_document_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_act_counterparty_id'))

    op.drop_table('reconciliation_act')
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_payment_document_id'))
        batch_op.drop_index(batch_op.f('ix_counterparty_payment_date'))
        batch_op.drop_index(batch_op.f('ix_counterparty_payment_counterparty_id'))
        batch_op.drop_index(batch_op.f('ix_counterparty_payment_bank_account_id'))

    op.drop_table('counterparty_payment')
    # ### end Alembic commands ###
