"""drop cooperative balance fields

Revision ID: 9fda27835c78
Revises: 681177a9a365
Create Date: 2026-08-19 04:29:37.703009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fda27835c78'
down_revision: Union[str, Sequence[str], None] = '681177a9a365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.drop_column('balance_updated_at')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooperative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('balance_updated_at', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
