"""add bank api integration

Revision ID: a1f14574f3e5
Revises: 0c64b99b76f4
Create Date: 2026-08-24 18:33:47.653281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f14574f3e5'
down_revision: Union[str, Sequence[str], None] = '0c64b99b76f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_api_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('sandbox', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('last_balance_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_statement_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_bank_api_credential_bank_account_id_bank_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_api_credential')),
    sa.UniqueConstraint('bank_account_id', name=op.f('uq_bank_api_credential_bank_account_id'))
    )
    op.create_table('bank_statement_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('external_uid', sa.String(length=64), nullable=True),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_inn', sa.String(length=12), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_bank_statement_line_bank_account_id_bank_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_statement_line')),
    sa.UniqueConstraint('bank_account_id', 'external_uid', name='uq_bank_statement_line_external_uid')
    )
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_line_bank_account_id'), ['bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_line_operation_date'), ['operation_date'], unique=False)

    op.create_table('charge_registry_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'ERROR', name='chargeregistrystatus'), nullable=False),
    sa.Column('charges_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bank_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_charge_registry_batch_bank_account_id_bank_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charge_registry_batch'))
    )
    with op.batch_alter_table('charge_registry_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_registry_batch_bank_account_id'), ['bank_account_id'], unique=False)

    op.create_table('payment_registry_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('matched_payment_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_payment_registry_entry_bank_account_id_bank_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['payment.id'], name=op.f('fk_payment_registry_entry_matched_payment_id_payment'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_registry_entry')),
    sa.UniqueConstraint('bank_account_id', 'external_id', name='uq_payment_registry_entry_external_id')
    )
    with op.batch_alter_table('payment_registry_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_registry_entry_bank_account_id'), ['bank_account_id'], unique=False)

    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        # server_default нужен только на время добавления колонки — у уже
        # существующих счетов (если это не первый деплой) API до этой
        # миграции нигде не был выбран, значение по умолчанию — NONE (имя
        # члена перечисления, а не его .value "none" — так же хранятся все
        # Enum-колонки в проекте, см. RoleEnum). Дальше убираем
        # server_default: на уровне приложения значение всегда задаётся явно
        # (BankAccount.api_provider = BankApiProvider(...) / default=BankApiProvider.NONE
        # в модели), потребности держать его в схеме БД нет.
        batch_op.add_column(sa.Column(
            'api_provider',
            sa.Enum('NONE', 'SBERBANK', 'VTB', 'TBANK', name='bankapiprovider'),
            nullable=False, server_default='NONE',
        ))
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.alter_column('api_provider', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_column('api_provider')

    with op.batch_alter_table('payment_registry_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_registry_entry_bank_account_id'))

    op.drop_table('payment_registry_entry')
    with op.batch_alter_table('charge_registry_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_registry_batch_bank_account_id'))

    op.drop_table('charge_registry_batch')
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_operation_date'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_bank_account_id'))

    op.drop_table('bank_statement_line')
    op.drop_table('bank_api_credential')
    # ### end Alembic commands ###
