"""add control meters tree

Внутренние контрольные счётчики кооператива для сверки показаний (без
начислений) — иерархическое дерево (control_meter.parent_id, self-FK по
образцу wiki_page.parent_id) + история показаний (control_meter_reading) +
привязка ветви гаражей к узлу (garage.control_meter_id, NULL по умолчанию —
обратная совместимость). См. app/control_meters.py.

Revision ID: c66bd8825ef2
Revises: 2a3c649e8b11
Create Date: 2026-09-04 00:20:29.903157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66bd8825ef2'
down_revision: Union[str, Sequence[str], None] = '2a3c649e8b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['control_meter.id'], name=op.f('fk_control_meter_parent_id_control_meter'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_control_meter'))
    )
    with op.batch_alter_table('control_meter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_meter_parent_id'), ['parent_id'], unique=False)

    op.create_table('control_meter_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_meter_id', sa.Integer(), nullable=False),
    sa.Column('reading', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['control_meter_id'], ['control_meter.id'], name=op.f('fk_control_meter_reading_control_meter_id_control_meter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_control_meter_reading'))
    )
    with op.batch_alter_table('control_meter_reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_meter_reading_control_meter_id'), ['control_meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_meter_reading_reading_date'), ['reading_date'], unique=False)

    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_meter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_garage_control_meter_id'), ['control_meter_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_garage_control_meter_id_control_meter'), 'control_meter', ['control_meter_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_garage_control_meter_id_control_meter'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_garage_control_meter_id'))
        batch_op.drop_column('control_meter_id')

    with op.batch_alter_table('control_meter_reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_meter_reading_reading_date'))
        batch_op.drop_index(batch_op.f('ix_control_meter_reading_control_meter_id'))

    op.drop_table('control_meter_reading')
    with op.batch_alter_table('control_meter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_meter_parent_id'))

    op.drop_table('control_meter')
    # ### end Alembic commands ###
