"""add counterparty api provider and external balance

Revision ID: c9ecc27410dc
Revises: 9d3e5c8a2f14
Create Date: 2026-09-14 10:29:34.933429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ecc27410dc'
down_revision: Union[str, Sequence[str], None] = '9d3e5c8a2f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        # server_default нужен только на время добавления колонки — у уже
        # существующих контрагентов (если это не первый деплой) API до этой
        # миграции нигде не был выбран, значение по умолчанию — NONE (имя
        # члена перечисления, а не его .value "none" — так же хранятся все
        # Enum-колонки в проекте, см. BankApiProvider/RoleEnum). Дальше
        # убираем server_default: на уровне приложения значение всегда
        # задаётся явно (Counterparty.api_provider = CounterpartyApiProvider(...)
        # / default=CounterpartyApiProvider.NONE в модели), потребности
        # держать его в схеме БД нет.
        batch_op.add_column(sa.Column(
            'api_provider',
            sa.Enum('NONE', 'SMSAERO', name='counterpartyapiprovider'),
            nullable=False, server_default='NONE',
        ))
        batch_op.add_column(sa.Column('external_balance', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('external_balance_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('external_balance_error', sa.Text(), nullable=True))
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.alter_column('api_provider', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.drop_column('external_balance_error')
        batch_op.drop_column('external_balance_updated_at')
        batch_op.drop_column('external_balance')
        batch_op.drop_column('api_provider')

    # ### end Alembic commands ###
