"""restructure power phase reading: drop raw_params, add day_kwh/month_kwh/sled_online/switch_on

Revision ID: cb7a84c0532f
Revises: b73e867121be
Create Date: 2026-09-03 09:29:01.531430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7a84c0532f'
down_revision: Union[str, Sequence[str], None] = 'b73e867121be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 'cooperative.garage_area' drop вырезан вручную — это не наше изменение,
    # а посторонний дрейф dev-БД (колонка убрана из модели уже давно, в
    # миграции 2a97e92adbab, но в БД этой сессии почему-то ещё жива) —
    # повторяется в каждом autogenerate этой сессии, см. историю коммитов.
    with op.batch_alter_table('power_phase_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_kwh', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('month_kwh', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sled_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('switch_on', sa.Boolean(), nullable=True))
        batch_op.drop_column('raw_params')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power_phase_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_params', sa.TEXT(), nullable=True))
        batch_op.drop_column('switch_on')
        batch_op.drop_column('sled_online')
        batch_op.drop_column('month_kwh')
        batch_op.drop_column('day_kwh')

    # ### end Alembic commands ###
