"""add mailbox settings

Параметры подключения к общему почтовому ящику правления (IMAP/POP3 +
SMTP) — см. app/mail_client.py, app/mailbox.py. Одна запись, письма не
кэшируются в БД, только сами настройки подключения.

Revision ID: d3b61bbcf71d
Revises: 61dfe5611269
Create Date: 2026-09-04 09:58:10.409568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b61bbcf71d'
down_revision: Union[str, Sequence[str], None] = '61dfe5611269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_protocol', sa.Enum('IMAP', 'POP3', name='mailprotocol'), nullable=False),
    sa.Column('incoming_host', sa.String(length=255), nullable=True),
    sa.Column('incoming_port', sa.Integer(), nullable=False),
    sa.Column('incoming_encryption', sa.Enum('SSL', 'STARTTLS', 'NONE', name='mailencryption'), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_encryption', sa.Enum('SSL', 'STARTTLS', 'NONE', name='mailencryption'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailbox_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailbox_settings')
    # ### end Alembic commands ###
