"""add configurable registry file format

Revision ID: d78a43b35267
Revises: 3a1d3637b8da
Create Date: 2026-08-25 10:14:52.001209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78a43b35267'
down_revision: Union[str, Sequence[str], None] = '3a1d3637b8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_registry_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('charge_columns', sa.Text(), nullable=False),
    sa.Column('payment_columns', sa.Text(), nullable=False),
    sa.Column('charge_decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('payment_decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('delimiter', sa.String(length=1), nullable=False),
    sa.Column('encoding', sa.String(length=20), nullable=False),
    sa.Column('trailer_prefix', sa.String(length=10), nullable=True),
    sa.Column('service_code', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_bank_registry_format_bank_account_id_bank_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_registry_format')),
    sa.UniqueConstraint('bank_account_id', name=op.f('uq_bank_registry_format_bank_account_id'))
    )
    with op.batch_alter_table('payment_registry_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credited_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_registry_entry', schema=None) as batch_op:
        batch_op.drop_column('fee_amount')
        batch_op.drop_column('credited_amount')

    op.drop_table('bank_registry_format')
    # ### end Alembic commands ###
