"""add bulletin attachments and members-only flag

Revision ID: db0345965ad2
Revises: df45e1c51ebc
Create Date: 2026-09-08 12:34:02.742598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0345965ad2'
down_revision: Union[str, Sequence[str], None] = 'df45e1c51ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_bulletin_attachment_author_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['bulletin_post.id'], name=op.f('fk_bulletin_attachment_post_id_bulletin_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulletin_attachment'))
    )
    with op.batch_alter_table('bulletin_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulletin_attachment_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulletin_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulletin_attachment_is_inline'), ['is_inline'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulletin_attachment_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('bulletin_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_members_only', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_bulletin_post_is_members_only'), ['is_members_only'], unique=False)
    with op.batch_alter_table('bulletin_post', schema=None) as batch_op:
        batch_op.alter_column('is_members_only', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulletin_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulletin_post_is_members_only'))
        batch_op.drop_column('is_members_only')

    with op.batch_alter_table('bulletin_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulletin_attachment_post_id'))
        batch_op.drop_index(batch_op.f('ix_bulletin_attachment_is_inline'))
        batch_op.drop_index(batch_op.f('ix_bulletin_attachment_created_at'))
        batch_op.drop_index(batch_op.f('ix_bulletin_attachment_author_id'))

    op.drop_table('bulletin_attachment')
    # ### end Alembic commands ###
