"""remove board member accountant flag, accountant appointed by chairman separately

Revision ID: dbc01b5009be
Revises: 9fda27835c78
Create Date: 2026-08-19 09:34:01.921122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc01b5009be'
down_revision: Union[str, Sequence[str], None] = '9fda27835c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.drop_column('is_accountant')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accountant', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###
