"""add electronic voting: vote, vote_question, vote_ballot

Revision ID: df225edbffbd
Revises: 9a4dfa67d711
Create Date: 2026-08-21 11:47:45.390183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df225edbffbd'
down_revision: Union[str, Sequence[str], None] = '9a4dfa67d711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voting_type', sa.Enum('IN_PERSON_AND_ABSENTEE', 'ABSENTEE', name='votetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='votestatus'), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_person_id', sa.Integer(), nullable=True),
    sa.Column('protocol_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['person.id'], name=op.f('fk_vote_created_by_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['general_meeting.id'], name=op.f('fk_vote_meeting_id_general_meeting'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_document_id'], ['document.id'], name=op.f('fk_vote_protocol_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote'))
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_created_by_person_id'), ['created_by_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_protocol_document_id'), ['protocol_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_status'), ['status'], unique=False)

    op.create_table('vote_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('majority_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], name=op.f('fk_vote_question_vote_id_vote'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_question'))
    )
    with op.batch_alter_table('vote_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_question_vote_id'), ['vote_id'], unique=False)

    op.create_table('vote_ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', name='votechoice'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('cast_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_vote_ballot_person_id_person')),
    sa.ForeignKeyConstraint(['question_id'], ['vote_question.id'], name=op.f('fk_vote_ballot_question_id_vote_question'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_ballot')),
    sa.UniqueConstraint('question_id', 'person_id', name='uq_vote_ballot_question_person')
    )
    with op.batch_alter_table('vote_ballot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_ballot_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_ballot_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_ballot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_ballot_question_id'))
        batch_op.drop_index(batch_op.f('ix_vote_ballot_person_id'))

    op.drop_table('vote_ballot')
    with op.batch_alter_table('vote_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_question_vote_id'))

    op.drop_table('vote_question')
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_status'))
        batch_op.drop_index(batch_op.f('ix_vote_protocol_document_id'))
        batch_op.drop_index(batch_op.f('ix_vote_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_vote_created_by_person_id'))

    op.drop_table('vote')
    # ### end Alembic commands ###
