"""add bulletin board

Revision ID: df45e1c51ebc
Revises: 339bc8ea5507
Create Date: 2026-09-08 12:01:30.110584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df45e1c51ebc'
down_revision: Union[str, Sequence[str], None] = '339bc8ea5507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('BUY', 'SELL', 'RENT', 'SERVICES', name='bulletincategory'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_bulletin_post_author_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulletin_post'))
    )
    with op.batch_alter_table('bulletin_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulletin_post_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulletin_post_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulletin_post_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulletin_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulletin_post_created_at'))
        batch_op.drop_index(batch_op.f('ix_bulletin_post_category'))
        batch_op.drop_index(batch_op.f('ix_bulletin_post_author_id'))

    op.drop_table('bulletin_post')
    # ### end Alembic commands ###
