"""add adjusts_bank_balance to counterparty_payment

Revision ID: e24720fd94ed
Revises: cb7a84c0532f
Create Date: 2026-09-03 10:15:31.197262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24720fd94ed'
down_revision: Union[str, Sequence[str], None] = 'cb7a84c0532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 'cooperative.garage_area' drop вырезан вручную — это не наше изменение,
    # а посторонний дрейф dev-БД (колонка убрана из модели уже давно, в
    # миграции 2a97e92adbab, но в БД этой сессии почему-то ещё жива) —
    # повторяется в каждом autogenerate этой сессии, см. историю коммитов.
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        # server_default нужен только на время добавления колонки — у уже
        # существующих платежей поведение до этой миграции было ровно
        # «списываем со счёта всегда», это и есть True.
        batch_op.add_column(sa.Column('adjusts_bank_balance', sa.Boolean(), nullable=False, server_default=sa.true()))
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.alter_column('adjusts_bank_balance', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty_payment', schema=None) as batch_op:
        batch_op.drop_column('adjusts_bank_balance')

    # ### end Alembic commands ###
