"""add wiki page tree, replace flat category

Заменяет плоскую произвольную категорию (WikiPage.category, свободный
текст) на дерево разделов/подразделов (WikiPage.parent_id, self-referencing
FK) — см. app/wiki.py и app/models.py:WikiPage для устройства дерева и
навигации.

Бэкофилл данных: для каждого уже использованного значения category
создаётся НОВАЯ страница-раздел с этим названием (пустое тело,
is_internal=False по умолчанию — правление может донастроить вручную), и
все страницы с этой категорией становятся её детьми (parent_id). Если
category нигде не использовалась (свежий деплой, пустая таблица) — цикл
бэкофилла просто не выполняется, никаких лишних страниц не появляется.

Revision ID: e80abefa5b98
Revises: 3d0ecf5086aa
Create Date: 2026-08-30 09:59:45.224150

"""
import datetime as dt
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80abefa5b98'
down_revision: Union[str, Sequence[str], None] = '3d0ecf5086aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Шаг 1: добавляем parent_id как обычную nullable-колонку — FK/индекс
    # добавим позже отдельным batch-проходом (шаг 3), после того как в неё
    # будут проставлены значения бэкофилла (шаг 2). Так надёжнее, чем
    # пытаться раскидать данные внутри самого batch-пересоздания таблицы.
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))

    # Шаг 2: бэкофилл — старые category становятся корневыми разделами.
    rows = conn.execute(sa.text(
        "SELECT DISTINCT category FROM wiki_page WHERE category IS NOT NULL"
    )).fetchall()

    now = dt.datetime.utcnow().isoformat(sep=" ")
    created = 0
    for row in rows:
        category = row[0]
        result = conn.execute(sa.text(
            "INSERT INTO wiki_page (title, body, is_internal, created_at, parent_id) "
            "VALUES (:title, '', 0, :now, NULL)"
        ), {"title": category, "now": now})
        new_section_id = result.lastrowid
        conn.execute(sa.text(
            "UPDATE wiki_page SET parent_id = :pid WHERE category = :category"
        ), {"pid": new_section_id, "category": category})
        created += 1

    print(f"Категорий превращено в корневые разделы дерева вики: {created}")

    # Шаг 3: убираем category и её индекс, добавляем индекс/FK на parent_id.
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_category'))
        batch_op.create_index(batch_op.f('ix_wiki_page_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_wiki_page_parent_id_wiki_page'), 'wiki_page', ['parent_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('category')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_wiki_page_parent_id_wiki_page'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wiki_page_parent_id'))
        batch_op.create_index(batch_op.f('ix_wiki_page_category'), ['category'], unique=False)
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
    # Примечание: downgrade НЕ восстанавливает category из имён
    # созданных при upgrade разделов — данные необратимо переходят в
    # структуру дерева. Это осознанное ограничение (как и почти всегда
    # с downgrade реальных данных, а не только схемы) — если совсем нужно
    # откатиться, категории придётся расставить руками по бэкапу.
