"""add penalty amnesty

Амнистия пени по годам (penalty_amnesty: год + дата конца, начало — срок
оплаты взносов этого года по уставу) и payment.amnesty_for_charge_id —
связь списания пени по амнистии с начислением, пеня по которому списана
(см. app/penalty.py: reconcile_amnesty_write_offs).

Revision ID: f1151ccf7863
Revises: 634893d30483
Create Date: 2026-09-23 23:25:29.841637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1151ccf7863'
down_revision: Union[str, Sequence[str], None] = '634893d30483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalty_amnesty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_penalty_amnesty'))
    )
    with op.batch_alter_table('penalty_amnesty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalty_amnesty_year'), ['year'], unique=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amnesty_for_charge_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_amnesty_for_charge_id'), ['amnesty_for_charge_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_payment_amnesty_for_charge_id_charge'), 'charge', ['amnesty_for_charge_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_amnesty_for_charge_id_charge'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_amnesty_for_charge_id'))
        batch_op.drop_column('amnesty_for_charge_id')

    with op.batch_alter_table('penalty_amnesty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalty_amnesty_year'))

    op.drop_table('penalty_amnesty')
    # ### end Alembic commands ###
