"""add counterparty to document

Revision ID: f14327a9e7f5
Revises: 2b97a3a3dd71
Create Date: 2026-09-02 09:50:24.818489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14327a9e7f5'
down_revision: Union[str, Sequence[str], None] = '2b97a3a3dd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_document_counterparty_id_counterparty'), 'counterparty', ['counterparty_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_counterparty_id_counterparty'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_document_counterparty_id'))
        batch_op.drop_column('counterparty_id')

    # ### end Alembic commands ###
