"""add sms settings and verification code tables

Новые таблицы — обе новые, без бэкофилла:
- sms_settings: настройки СМС-провайдера (SMS Aero), см. app/sms/.
- verification_code: одноразовые коды подтверждения телефона при
  самостоятельной регистрации и восстановления пароля, см.
  app/verification.py.

Revision ID: fa52a847d8a6
Revises: 1d2c69d8ddb7
Create Date: 2026-09-06 13:16:25.966909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa52a847d8a6'
down_revision: Union[str, Sequence[str], None] = '1d2c69d8ddb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('SMSAERO', name='smsprovider'), nullable=False),
    sa.Column('smsaero_email', sa.String(length=255), nullable=True),
    sa.Column('smsaero_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('sender_sign', sa.String(length=50), nullable=True),
    sa.Column('last_test_result', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_settings'))
    )
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('PHONE_REGISTER', 'PASSWORD_RESET', name='verificationcodepurpose'), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_code'))
    )
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_code_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_code_target'), ['target'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_code_target'))
        batch_op.drop_index(batch_op.f('ix_verification_code_purpose'))

    op.drop_table('verification_code')
    op.drop_table('sms_settings')
    # ### end Alembic commands ###
